# Generated by Django 6.0.7 on 2026-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationreport',
            name='business_analysis',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='final_report',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='market_analysis',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='risk_analysis',
            field=models.JSONField(),
        ),
    ]
