# Generated by Django 6.0.7 on 2026-07-14 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_alter_validationreport_business_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
