# Generated by Django 6.0.7 on 2026-07-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_revokedrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='final_verdict',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='validator.startupidea'),
        ),
    ]
